language: node_js
node_js:
- stable
- 5.4.1
- 5.4.0
- 5.3.0
- 5.2.0
- 5.1.1
- 4.4.6
before_install:
- npm install -g typings
- npm install -g codeclimate-test-reporter
- typings install
after_success:
  codeclimate-test-reporter < coverage/lcov.info
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && 
      [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "Deploying application!"
    npm publish-please
  else
    echo "Skipping a deployment because this is not a tagged commit!"
  fi
