language: node_js
node_js:
- stable
- 4.2.3
- 4.2.0
- 4.1.2
- 4.1.0
- 4.0.0
- '0.12'
- '0.10'
before_install:
- npm install -g tsd
- tsd install
env:
  global:
    TSD_GITHUB_TOKEN:
    - secure: BBElDfUZV4/ipF8R1sAPClBtJnOWIrNBwKl2gs7n/054KGagWYNKBwUrbySrYWtunRF9CzUPnl9Tp5gXw+RU4rpgFaTiEexSh9TU3CuSexX9Oet1VrAZ3SOEWsrVZ3EF/Y2uZbQwE4JF/X8SwFmm5qcR0jWT9DpAuZRpxRkqy/T5vG8bK83nJAhydC3MwOcVrRqBBFzkpayBw8YQWHNCCDNfkOP7jGJU5K78d9S5UFrc8MaBnG9OVRrohlFpOfLFE3bWDuzlfgkMYSxxQQAfWbihA5krZ0E65550HU6clvUGirRoLNHDAefvKBq43OVp6U1ytm1VICkNB6gpBptUvjCA6quaQm5Vzbh9FTlkow/jRtyYWsuVIifr8WlFoWggbliJSBqqQo/k2Tqby9bZzDWN5HsXeaZWwut1d5Pon0b0z3Y2QW3rkT7yVMpC5traSjR7r9vMoZyMnlX+Bm4oo8qbADfKcOMKcdjHwQOxdp06+25FNOdm9vWH3/stPUETZi70TrsI9SMyRfkue6hiOg/fPuHdFw1vc01lxI6MEqmi6MOZQJCEPAuC9yxD5PAmeSQZjcqevrsw3o9bGRJdU/SK5QLSrIuyjvNupVTpkQBHLWRFTCL+mkRtMDT4PrdVAWDvdIrwmE9eqjakeYMnn4/laoq/2yTF2cwLXDIbOIQ=
