language: node_js
node_js:
- stable
- 4.2.3
- 4.2.0
- 4.1.2
- 4.1.0
- 4.0.0
- '0.12'
- '0.10'
before_install:
- npm install -g tsd
- tsd install
env:
  global:
  - secure: XZ+/yUq1FlSO+s2QWZSPMxWj+AQ5IdZboM+mmOTqcxQDl4bXY5iTwzbyvg2972wYanGRWvIy6o+U7S1R5htKW3MCJLIAnTCHxkTJ1Y+lRroBcwAVxir1KU+IPZtsapTSYETIWNafBiVCQ6h9oCyOavk/trH6GyuoVFHqM6CdqlTxI8hB3ToQEmDnocVvsNb3RIPYv1BsUc8O41Y8/N1jD7n/+40Y+oboni9nWVytl8o9E+SBQYCAtNVfCOBtWEz8ycfRd4kr7gMZTBwBNQQW+owXLzcPGhF6ohMz895fbjXrXRIMnLVUgmk8Qgn2Kkiw1v0UQw6LeZ+DRLCFlS2vhMaltPpRxhgmPDz8et1jJJz6lkojCVYQr3tWMsDnJa0vpIutdZnhfapLv8pYZFSZ6l2h3Y1Nz5PGzWe/TgoF3iHTyYp6wE3OVo8UGAih4xnJeJzhuugmFkwknxELlTZ1sYXTHv61NxmoP+0B3svXh4wE1IwpdoIaJ+6jGcT4NSI1tSM0bPDjNGfUuJQokNcHFkdb1/eAf0ykGaTfbQB4tLw3AWO0fuP4fZ8NKR/n0Fbra9KH1c6aItb1ELripZImSLc0Z45GxdwYZRN6Pie4rO3LK9TnKAttTxiVT/35AI9CWPB/VQtAuZRqn8HUnSSqpVdEzMeJ/9rVD0DUsaWn3No=
