language: node_js
node_js:
- stable
- 4.2.3
- 4.2.0
- 4.1.2
- 4.1.0
- 4.0.0
- '0.12'
- '0.10'
before_install:
- npm install -g tsd
- tsd install
env:
  global:
    secure: O5ctsejFHsd6fUcQXkpBf53WDyY1uMyHkz76lAzOO7kgPyyEHe7lJCpgHLxAVB/xqNwnI0i18HnrnOnhlu1FmGgfSeIAPWyAgHkgJDxKLPGWRy3H89TPWOE8oVgviEH78gj7GCYty4cE9OsQig6pv2zlh3hRGjRR7doAg4/35CjFUPczGuaPrxQ7jywN52oLdPmbHhmyS8x0V/cQUR0FLDkNUdLp+FqsJFCG1OARgentkr4fdduALtnQaYYHc3XQAHUaxc7Kexaz4mGzkDuuDGnnB5XZ9afKNvO0DVH+K8kIVPPkzpYG4NRexqQaA/9sVZ7Ta/AFXGwdYknEJtiFsDWB/UntLHbH25aJt98tSp+Q3Db4oFmnUkfdKob0m/88g5I5pjGkWMsQFcUstZa74RBushbzf1RoPC5eAmi44K8oO8E9BDDT3TweYTQn293R4/4/d/7cxSbJt0958zNv39FwR4TPmurqeTtjAnQniQXTe9S/ezw/ijBZ66AuRFGux9bq5Pc3qQkNNJd1zNqd04d3TCfaQhxxXEen4G5flmqI94ZBFFUPfFcgD5Jh1pHoToQQqc6P8w0WkhMYj3XZ9VOsaRy4QkkQrmGN0sVGPH5JSUW9mwplrdBq/+V+Indp8jX7vJmqCDrSQ8H3IFnT612OAj2S73iIuq2ck7W5QPc=
