language: node_js
node_js:
- stable
- 4.2.3
- 4.2.0
- 4.1.2
- 4.1.0
- 4.0.0
- '0.12'
- '0.10'
before_install:
- npm install -g tsd
- tsd install
env:
  global:
    - secure: dYTU+eot2vEKl2a6rGJNN4hlwNSr1RM7+wKOacKTObVbCpGP696uSAvksfG27R+Jk/tFiH6xEzwkbI6EEwrEpMcdjIF0cXR0JDl6rKKwDw3U0rghbyfTh3i2lGhcLv+bXN5h+Q5HHlJq7wxfYByXdH0n8Np3hgcYIf8Lzz6K3ZszRxTXFhDBarxmFx+0/gRymyHI+6GZlp9h9C6Px+9V9jYOMTvpfRHCJkvAvF+9L1BRkxkSaqw2wSvB+ZjBlBNDWi6w9ePtp4IS4INl3znnTX6iYRn74unRsT5pR5fnCu+3CtU06QBDqbQ+9WzcaXrKT4qUuKsUFiVKeE+uk97c46/dHRhWd+9DAaRmRBO6ECQXMP1CG+ykv7HplguRiTV5X4+yrEub87jDzVilPf3AgMgpN9bxtQuikZwzl25qpt9efRgmJCik9jvSFpw57i+hEA7wShXLjuKhsrJWhQERkKfIoyh/0CZT3L7Szo//myQjRt2nk7JuD351Ah3q7w7cjAGLnRhY0md2jfhTWmv0hK/bGKpLgUMB3E9JgdAY8/CGCY39KclCz7W2Bgcb0K6tuFt6/whX09Bjnsc1C7PkuyZdjeoaDvo+hETRUM8+byqsRbjDwQuanUHcNwjB+UrVCRkkA3X0JALlm7J5+2HuapWrh1kISx6W0eRMQxI0mDk=
