language: node_js
node_js:
- stable
- 4.2.3
- 4.2.0
- 4.1.2
- 4.1.0
- 4.0.0
- '0.12'
- '0.10'
before_install:
- npm install -g tsd
- tsd install
env:
  global:
  - secure: AXI7DWd3iH9KKzqsDIagd30DYalP2wiYXaDmiS6A3Afn6cOab8Bjh3Hxq1lIwME8zIR4AV+ZcIkIwmXPaNUShk47lAwja6L2npPf2uUEzKAuA9XeO8zYBIQpm2zy+kpG3VMxA3Khp3M5VxKkKS67BNMo4Lh507xTu529/zQxT/Q=
